name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag talshaham/simple_weather_image:${{ github.run_id }}
    - name: Log in to Docker Hub
      run: echo "tal123456" | docker login -u "talshaham" --password-stdin
    - name: Push Docker image to Docker Hub
      run: docker push talshaham/simple_weather_image:${{ github.run_id }}
